# Generated by Django 4.0.2 on 2022-04-18 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_orderitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantiti',
            new_name='quantity',
        ),
    ]
